spring.application.name=spring-calismalar

# Veritabanı Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
# 'update' sayesinde sen Java kodu yazdıkça tabloların otomatik oluşur.
spring.jpa.hibernate.ddl-auto=update
# Konsolda SQL sorgularını görebilmek için:
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Postgres lehçesini (dialect) belirtiyoruz:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect